POST https://backend-eosin-phi.vercel.app/login HTTP/1.1
content-type: application/json

{
    "email": "adm@sitesdigitais.com",
    "password": "123456"
}

GET https://backend-eosin-phi.vercel.app/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzMzkwOSwiZXhwIjoxNjUwMjM3NTA5LCJzdWIiOiIyIn0.nS99u-MBatZHbexMUenwsGdS8oV55BIaGwI6PSP7BC8


